name: skin_disease_app
description: Skin Disease detection for Congressional App Challenge

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0 
  shared_preferences: ^2.0.15 
  image_picker: ^0.8.7+3
  english_words: ^4.0.0
  provider: ^6.0.0
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_pytorch: ^1.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true